url = "https://news.ycombinator.com/news"

[items]
selector = "tr.athing"

[items.rank]
selector = "span.rank"
target = "text"
regex = "(^\\d+)."

[items.title]
selector = "span.titleline>a"
target = "inner_html"


